### ISSUE TITLE
Split config into multiple files for more flexibility and much better convenience for networks with a lot of subservers

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [efekurbann/sync-commands#7]
First config called `config.yml`, contains current server's data:
```yml
serverName: "testServer" # anything you want

connection: # connection to listen for new commands
  # currently there are 3 different types; socket, redis and rabbitmq.
  # you must use the same type as the other servers, otherwise it wont work.
  type: socket
  host: "localhost"
  port: 1234
  password: "supersecretpassword"
  secure: true # if you are going to use socket, I highly recommend you to keep this enabled and change the password.

  # these settings are only for RabbitMQ, if you are not going to use RabbitMQ just ignore this section.
  username: "guest"
  vhost: "/"
```

Second config called `servers.yml`, contains all other (or current too) servers' data:
```yml
servers: # connections to send commands, not listen
  server1: # command would be /(b)sync server1 {command}
    host: "localhost"
    port: 1235
    password: "supersecretpassword"
    secure: true
  server2: # command would be /(b)sync server2 {command}
    host: "localhost"
    port: 1236
    password: "supersecretpassword"
    secure: true
#  testServer: # command would be /(b)sync testServer {command}
#    host: "localhost"
#    port: 13861
#    password: "supersecretpassword"
#    secure: false
#
# you are able to add the current server, but it is disabled by default because it may not be useful for everyone
```

Third config called: `groups.yml`, contains group of servers:
```yml
groups:
  skyblock:
    - server1 # it has to be the target server's name. case sensitive.
    - server2
  bedwars:
    - server3
    - server4
  proxy: # You have more than one proxy? Don't worry!
    - bungee1
    - bungee2

no-permission: "&cYou do not have enough permission to perform this command!"
```

I think this is much more convenient way of doing things, makes life easier if you have 50+ servers and want to install on each one of them especially for `servers.yml` and `groups.yml` because you can just define the whole list of all servers that you have and copy-paste file around... only editing `config.yml` which is current server's data

NOTE:
Even if this gets added, please do not change option to allow adding current server's data into `servers.yml` too!
